version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      deps:
        patterns:
          - "*"
          - "msw"
          - "pactum"
          - "@nestjs/*"
          - "@shevernitskiy/*"
          - "cdek"
          - "google-auth-library"
          - "google-spreadsheet"
          - "grammy"
          - "handlebars"
          - "nest-winston"
          - "nodemailer"
          - "number-to-words-ru"
          - "pdf-lib"
          - "tar-fs"
          - "winston"
          - "winston-daily-rotate-file"
