version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      deps:
        patterns:
          - "*"
        exclude-patterns:
          - "*eslint*"
          - "*vitest*"
